apiVersion: v1
kind: Service
metadata:
  name: budget-service
  labels:
    app: budget-service
spec:
  type: ClusterIP
  selector:
    app: budget-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9003
